### PR TITLE
Fix String() bug for non-int negative numbers

### LINKED ISSUE #62: Malformed String() result for negative number
screen_shot_2018-02-07_at_10_40_49_am

screen_shot_2018-02-07_at_10_41_33_am

screen_shot_2018-02-07_at_10_41_03_am

screen_shot_2018-02-07_at_10_48_34_am

### PR DESCRIPTION
**Pull request by workmajj**
Fixes #62

### CODE REVIEW

File: values.go [hunk 1]
```diff
@@ -150,6 +161,9 @@ func (value *Number) String() string {
 		l      = len(s)
 		buffer bytes.Buffer
 	)
+	if negative {
```
Comment (pascallouisperez) [inline values.go]: We don't need `negative`, simply use `value.value < 0`

File: values.go [hunk 2]
```diff
@@ -133,10 +133,21 @@ func (value *Number) Equal(that Value) bool {
...
+	}
+
+	var (
+		s        string
+		negative bool
+	)
+
+	if value.value < 0 {
+		s = strconv.FormatInt(-value.value, 10)
+		negative = true
```
Comment (pascallouisperez) [inline values.go]: minor: if you more the `buffer` declaration along with `s` (in the `var`) block, you can both instantiate `s` and `buffer.WriteRune('-')` in the same `if`
